### ISSUE TITLE
Error while using script

### ISSUE THREAD

**Issue by HydraTheShibe** [D4Vinci/elpscrk#3]
I was using the script to generate a password list and it and it gave me this error

Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "elpscrk.py", line 68, in main
    oo1=all(f1,f2,num)
  File "elpscrk.py", line 26, in all
    now_fuck(lol,latest,n)
  File "elpscrk.py", line 24, in now_fuck
    za3bola=[''.join(x for x in t) for t in itertools.product(latest_fuckin_thing,repeat=n)]
MemoryError

**Comment by D4Vinci** [comment]
Elpscrk is new tool now, check it out.
